const List = [
  { value: 'ACCIONA', label: 'Acciona' },
  { value: 'ACERINOX', label: 'Acerinox' },
  { value: 'ACS', label: 'ACS' },
  { value: 'AENA', label: 'Aena' },
  { value: 'AMADEUS IT GROUP', label: 'Amadeus IT Group' },
  { value: 'ARCELORMITTAL', label: 'Arcelormittal' },
  { value: 'BANCO SABADELL', label: 'Banco Sabadell' },
  { value: 'BANKIA', label: 'Bankia' },
  { value: 'BANKINTER', label: 'Bankinter' },
  { value: 'BBVA', label: 'BBVA' },
  { value: 'CAIXABANK', label: 'Caixabank' },
  { value: 'CELLNEX TELECOM', label: 'Cellnex Telecom' },
  { value: 'CIE AUTOMOTIVE', label: 'CIE Automotive' },
  { value: 'COLONIAL', label: 'Colonial' },
  { value: 'ENAGAS', label: 'Enagas' },
  { value: 'ENCE', label: 'ENCE' },
  { value: 'ENDESA', label: 'Endesa' },
  { value: 'FERROVIAL', label: 'Ferrovial' },
  { value: 'GRIFOLS', label: 'Grifols' },
  { value: 'IAG', label: 'IAG' },
  { value: 'IBERDROLA', label: 'Iberdrola' },
  { value: 'INDITEX', label: 'Inditex' },
  { value: 'INDRA', label: 'Indra' },
  { value: 'MAPFRE', label: 'Mapfre' },
  { value: 'MEDIASET', label: 'Mediaset' },
  { value: 'MELIA HOTELS', label: 'Melia Hotels' },
  { value: 'MERLIN PROP', label: 'Merlin Prop' },
  { value: 'NATURGY', label: 'Naturgy' },
  { value: 'RED ELECTRICA', label: 'Red eléctrica' },
  { value: 'REPSOL', label: 'Repsol' },
  { value: 'SANTANDER', label: 'Santander' },
  { value: 'SIEMENS', label: 'Siemens' },
  { value: 'TECNICAS REUNIDAS', label: 'Técnicas Reunidas' },
  { value: 'TELEFONICA', label: 'Telefónica' },
  { value: 'VISCOFAN', label: 'Viscofan' }
  
];

export default List