const List = [
  { value: 'MMM', label: '3M' },
  { value: 'AXP', label: 'American Express' },
  { value: 'AAPL', label: 'Apple' },
  { value: 'BA', label: 'Boeing' },
  { value: 'CAT', label: 'Caterpillar' },
  { value: 'CVX', label: 'Chevron' },
  { value: 'CSCO', label: 'Cisco' },
  { value: 'KO', label: 'Coca-Cola' },
  { value: 'DD-B', label: 'DuPont' },
  { value: 'DIS', label: 'Disney' },
  { value: 'XOM', label: 'ExxonMobil' },
  { value: 'GE', label: 'General Electric' },
  { value: 'GS', label: 'Goldman Sachs' },
  { value: 'HD', label: 'Home Depot' },
  { value: 'IBM', label: 'IBM' },
  { value: 'INTC', label: 'Intel' },
  { value: 'JNJ', label: 'Johnson & Johnson' },
  { value: 'JPM', label: 'JPMorgan' },
  { value: 'MCD', label: 'McDonald´s' },
  { value: 'MRK', label: 'Merck' },
  { value: 'MSFT', label: 'Microsoft' },
  { value: 'NKE', label: 'Nike' },
  { value: 'PFE', label: 'Pfizer' },
  { value: 'PG', label: 'Procter & Gamble' },
  { value: 'TRV', label: 'Travelers Companies, Inc.' },
  { value: 'UTX', label: 'United Technologies' },
  { value: 'UNH', label: 'UnitedHealth' },
  { value: 'VZ', label: 'Verizon' },
  { value: 'V', label: 'Visa' },
  { value: 'WMT', label: 'Wal-Mart' }
  
];

export default List